/**
 * AUTOMATICALLY GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-icon-types.js
 *
 * Type definition for icon names based on SVG files in public/assets/Icons directory
 */
export type IconName =
  | 'bootstrap'
  | 'expressjs'
  | 'figma'
  | 'flower'
  | 'git'
  | 'gsap'
  | 'javascript'
  | 'jwt'
  | 'mongodb'
  | 'mysql'
  | 'nextjs'
  | 'nodejs'
  | 'prisma'
  | 'reactjs'
  | 'sass'
  | 'tailwindcss'
  | 'trae'
  | 'typescript'
  | 'vscode';
